table CurrencySelector
	lineageTag: a5c47446-eb0a-4362-b9ce-adb82580a7f6

	column DisplayCurrencyCode
		dataType: string
		lineageTag: 6ef2fcc8-b9b7-4000-a9d1-f6c9dafc857f
		summarizeBy: none
		sourceColumn: DisplayCurrencyCode

		annotation SummarizationSetBy = Automatic

	column DisplayCurrencyName
		dataType: string
		lineageTag: 7739f374-16f0-425c-9151-cfb22ecafe4e
		summarizeBy: none
		sourceColumn: DisplayCurrencyName

		annotation SummarizationSetBy = Automatic

	partition CurrencySelector = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[CurrencySelector],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"DisplayCurrencyCode", type text}, {"DisplayCurrencyName", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

