table DataDictionary_Tables
	lineageTag: 225759b0-a669-420f-8967-dcd1e5d5cfbc

	column Table
		dataType: string
		lineageTag: e3d15b7e-85a3-44b1-802c-a70877f39f2b
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Rows
		dataType: int64
		formatString: 0
		lineageTag: 7c202df4-8d0a-470d-ad87-07fb6c120f09
		summarizeBy: none
		sourceColumn: Rows

		annotation SummarizationSetBy = Automatic

	column File
		dataType: string
		lineageTag: 12837b3e-f8ec-4355-816d-3bab72b047f5
		summarizeBy: none
		sourceColumn: File

		annotation SummarizationSetBy = Automatic

	column MainPurpose
		dataType: string
		lineageTag: db10322b-330c-441d-a081-9f7a7263812c
		summarizeBy: none
		sourceColumn: MainPurpose

		annotation SummarizationSetBy = Automatic

	partition DataDictionary_Tables = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[DataDictionary_Tables],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Table", type text}, {"Rows", Int64.Type}, {"File", type text}, {"MainPurpose", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

