table DataDictionary_Columns
	lineageTag: 8c6efb78-a8af-4c03-8b9b-3fb808c75a17

	column Table
		dataType: string
		lineageTag: 2d34ebc6-e2be-4a9f-bd2e-8a1a63b38fee
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Column
		dataType: string
		lineageTag: e1fe4982-b6f1-49d5-a835-74d0c2a800f5
		summarizeBy: none
		sourceColumn: Column

		annotation SummarizationSetBy = Automatic

	column SuggestedDataType
		dataType: string
		lineageTag: 415585d1-b5ae-45ed-af53-a61590fa09fc
		summarizeBy: none
		sourceColumn: SuggestedDataType

		annotation SummarizationSetBy = Automatic

	column SampleValue
		dataType: string
		lineageTag: a01c6b8b-1ad6-4211-a9e0-fb842749a54c
		summarizeBy: none
		sourceColumn: SampleValue

		annotation SummarizationSetBy = Automatic

	column Note
		dataType: string
		lineageTag: 6075638d-b70f-498e-bcaa-8dfd27def837
		summarizeBy: none
		sourceColumn: Note

		annotation SummarizationSetBy = Automatic

	partition DataDictionary_Columns = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[DataDictionary_Columns],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Table", type text}, {"Column", type text}, {"SuggestedDataType", type text}, {"SampleValue", type text}, {"Note", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

