table DimAccount
	lineageTag: d3ac7734-e6e0-42a2-b4ef-1aa79b166ced

	column AccountKey
		dataType: int64
		formatString: 0
		lineageTag: 6a89db72-a45f-4cce-8b92-bcbe8bed04c4
		summarizeBy: count
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

	column AccountName
		dataType: string
		lineageTag: dcde1c49-3ccc-4680-a954-48a3553eb800
		summarizeBy: none
		sourceColumn: AccountName

		annotation SummarizationSetBy = Automatic

	column ParentAccountKey
		dataType: int64
		formatString: 0
		lineageTag: 87e20af5-7e16-4c33-87da-05ea4da7382b
		summarizeBy: count
		sourceColumn: ParentAccountKey

		annotation SummarizationSetBy = Automatic

	column AccountLevel
		dataType: int64
		formatString: 0
		lineageTag: e95805d0-d940-43d6-8452-09b66d047872
		summarizeBy: sum
		sourceColumn: AccountLevel

		annotation SummarizationSetBy = Automatic

	column UnaryOperator
		dataType: string
		lineageTag: ef8794d0-ca26-49db-81b4-03142cdba834
		summarizeBy: none
		sourceColumn: UnaryOperator

		annotation SummarizationSetBy = Automatic

	partition DimAccount = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[DimAccount],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"AccountKey", Int64.Type}, {"AccountName", type text}, {"ParentAccountKey", Int64.Type}, {"AccountLevel", Int64.Type}, {"UnaryOperator", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

