table DimEmployee
	lineageTag: fe5c60ee-d37e-4b76-874d-0c6e14f885eb

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: b2917f28-9a71-4c59-ad5c-3c351875812a
		summarizeBy: none
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: 6daa7759-20c9-4029-90b8-964ad3d4414c
		summarizeBy: none
		sourceColumn: EmployeeName

		annotation SummarizationSetBy = Automatic

	column ManagerEmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 1064feea-51a7-4b35-b39f-b8fd66b1f4f4
		summarizeBy: none
		sourceColumn: ManagerEmployeeKey

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		lineageTag: eb261b93-7d2d-406b-b5cd-eefbf3af1a29
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: a2cbcfb0-9df3-4781-97f8-61d65c4fcf1c
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7cf65616-06fb-4e8d-9a2f-550a25cee780
		summarizeBy: none
		sourceColumn: HireDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DimEmployee = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[DimEmployee],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"EmployeeKey", Int64.Type}, {"EmployeeName", type text}, {"ManagerEmployeeKey", Int64.Type}, {"Role", type text}, {"Department", type text}, {"HireDate", type date}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

