table DimInterest
	lineageTag: e57df235-b84d-449a-a7a1-74b7b18b7014

	column InterestKey
		dataType: int64
		formatString: 0
		lineageTag: fbfbc5f3-b3df-43b9-989c-a6414cd29b29
		summarizeBy: count
		sourceColumn: InterestKey

		annotation SummarizationSetBy = Automatic

	column InterestName
		dataType: string
		lineageTag: 6cf7c3f7-7b62-4c8c-9236-f024926a6177
		summarizeBy: none
		sourceColumn: InterestName

		annotation SummarizationSetBy = Automatic

	partition DimInterest = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[DimInterest],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"InterestKey", Int64.Type}, {"InterestName", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

