table DimProductSubcategory
	lineageTag: 996f4b97-424f-4c4b-85cf-f38fa2a16556

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: b2c62800-9c58-4d5a-bd31-865d8d5d01e6
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryName
		dataType: string
		lineageTag: b545710a-8138-4696-98b6-d0dcf35b6545
		summarizeBy: none
		sourceColumn: ProductSubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: cc9e01a1-8cbc-46e2-94e1-58822ae0aabc
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition DimProductSubcategory = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[DimProductSubcategory],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ProductSubcategoryKey", Int64.Type}, {"ProductSubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

