table DimProductCategory
	lineageTag: b6d5e2ac-e34e-44e6-b0e1-d63cbb1d844d

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: bbdde8d5-3f4a-423e-9960-827618874ba3
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductCategoryName
		dataType: string
		lineageTag: fba68216-1cbc-4733-bef5-0b927a1897ef
		summarizeBy: none
		sourceColumn: ProductCategoryName

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 2e14272e-80a7-4583-be13-43eb0e6657b5
		summarizeBy: none
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	partition DimProductCategory = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[DimProductCategory],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ProductCategoryKey", Int64.Type}, {"ProductCategoryName", type text}, {"SortOrder", Int64.Type}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

