table FactWebSession
	lineageTag: 258873d8-f864-4ee6-a494-7a2ee86f4bf6

	column SessionID
		dataType: string
		lineageTag: 5e5b0aa6-bf1a-43e8-b004-d1e0587ae5ad
		summarizeBy: none
		sourceColumn: SessionID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 4a1fd55d-eb73-470c-9d0b-7737d35b72d5
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 2273a9ad-b695-46ec-b8fe-634c3eb94f09
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column MarketingChannel
		dataType: string
		lineageTag: aa66e7c9-7721-4522-9a7c-e23d47a904d4
		summarizeBy: none
		sourceColumn: MarketingChannel

		annotation SummarizationSetBy = Automatic

	column DeviceType
		dataType: string
		lineageTag: b64a4b23-05fd-45b7-9db0-2681ef56ae41
		summarizeBy: none
		sourceColumn: DeviceType

		annotation SummarizationSetBy = Automatic

	column PageViews
		dataType: int64
		formatString: 0
		lineageTag: a8316b21-718e-4f1c-962a-8b09b9c6357b
		summarizeBy: sum
		sourceColumn: PageViews

		annotation SummarizationSetBy = Automatic

	column DurationSeconds
		dataType: int64
		formatString: 0
		lineageTag: e534f315-6221-494f-a08e-425969fb71ad
		summarizeBy: sum
		sourceColumn: DurationSeconds

		annotation SummarizationSetBy = Automatic

	column ConvertedOrderNumber
		dataType: string
		lineageTag: e07ff4b8-c988-48db-8e9f-0411e4be1a7a
		summarizeBy: none
		sourceColumn: ConvertedOrderNumber

		annotation SummarizationSetBy = Automatic

	column CampaignCode
		dataType: string
		lineageTag: 0d569724-201d-433b-876d-746b4e4b952f
		summarizeBy: none
		sourceColumn: CampaignCode

		annotation SummarizationSetBy = Automatic

	partition FactWebSession = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[FactWebSession],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"SessionID", type text}, {"DateKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"MarketingChannel", type text}, {"DeviceType", type text}, {"PageViews", Int64.Type}, {"DurationSeconds", Int64.Type}, {"ConvertedOrderNumber", type text}, {"CampaignCode", type text}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

