table FactSales
	lineageTag: f39acde3-e0b9-4901-979b-c9347810e04e

	column OrderLineID
		dataType: int64
		formatString: 0
		lineageTag: 7e3bf9cf-2af8-4428-9601-e4ad57f29d58
		summarizeBy: count
		sourceColumn: OrderLineID

		annotation SummarizationSetBy = Automatic

	column OrderNumber
		dataType: string
		lineageTag: 04f2b7c6-aa3b-4f32-81a7-c72637a8238f
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: string
		lineageTag: 869b7940-76a0-4703-af41-795f6b17b952
		summarizeBy: none
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: string
		lineageTag: aca183ec-758d-4deb-b064-dea0d1ad3ce6
		summarizeBy: none
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column DeliveryDateKey
		dataType: string
		lineageTag: 564f0278-7936-45ce-834e-d855e7ff7c41
		summarizeBy: none
		sourceColumn: DeliveryDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: fcc409f5-da6f-4480-8de1-41ea189c406c
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 586ddb4b-76ac-4da3-b3fb-6c87d18f540c
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: d02a0e71-f3da-49a8-9b9b-277aa56e5d25
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 89009d04-1e10-428d-85e8-9ce652b4825d
		summarizeBy: none
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column CurrencyCode
		dataType: string
		lineageTag: 8bc68ebe-1b7c-4fe8-bab7-9d2f64b8a737
		summarizeBy: none
		sourceColumn: CurrencyCode

		annotation SummarizationSetBy = Automatic

	column SalesChannel
		dataType: string
		lineageTag: 8a592b09-f4ba-4006-9ab7-c0f5dcda9022
		summarizeBy: none
		sourceColumn: SalesChannel

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 3741c42b-102e-411c-9da4-797f433ded68
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 8b05d328-e884-4ba6-80a7-53a248b16298
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column UnitCost
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 89ef05f3-7447-4668-b30f-385fb423b6b9
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column DiscountPct
		dataType: double
		lineageTag: b7c928af-657c-4c96-9ff5-d62b08b05c03
		summarizeBy: sum
		sourceColumn: DiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TaxRate
		dataType: double
		lineageTag: a25897f3-331c-4fd7-95ac-adf0238dd506
		summarizeBy: sum
		sourceColumn: TaxRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FreightAmount
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 48212ba4-cf07-4ddb-8beb-120a88293521
		summarizeBy: sum
		sourceColumn: FreightAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column SalesAmount
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: ce2ab983-d1b0-4533-9ac7-e0ecd0b8c056
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column CostAmount
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: d21d3b29-fe99-411d-a3f7-05d614aa92fd
		summarizeBy: sum
		sourceColumn: CostAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column TaxAmount
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: d32a1b19-4e86-493c-a2de-543c5c30782e
		summarizeBy: sum
		sourceColumn: TaxAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column GrossAmount
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: da2dec7d-9dbf-4735-a264-2d6e31935105
		summarizeBy: sum
		sourceColumn: GrossAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column HighCardinalityTrackingCode
		dataType: string
		lineageTag: 4ad63bce-0215-40d5-ad80-b88111d4f05e
		summarizeBy: none
		sourceColumn: HighCardinalityTrackingCode

		annotation SummarizationSetBy = Automatic

	partition FactSales = m
		mode: import
		queryGroup: Source_files
		source =
				let
				  Source = CsvTables[FactSales],
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"StoreKey", Int64.Type}, {"EmployeeKey", Int64.Type}, {"OrderLineID", Int64.Type}, {"Quantity", Int64.Type}, {"UnitPrice", Currency.Type}, {"UnitCost", Currency.Type}, {"DiscountPct", type number}, {"TaxRate", type number}, {"FreightAmount", Currency.Type}, {"SalesAmount", Currency.Type}, {"CostAmount", Currency.Type}, {"TaxAmount", Currency.Type}, {"GrossAmount", Currency.Type}})
				in
				  #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

